# Generated by Django 5.0.1 on 2024-01-15 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('regex', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Regexs',
            },
        ),
        migrations.CreateModel(
            name='Extract_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('data', models.TextField(max_length=4000)),
                ('regex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.regex')),
            ],
            options={
                'verbose_name_plural': 'Extract_codes',
            },
        ),
    ]
